branch-defaults:
  default:
    environment: Rotememorization-env
environment-defaults:
  Rotememorization-env:
    branch: null
    repository: null
global:
  application_name: Rotememorization
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
